name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Bump version (if manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ github.event.inputs.version_type }}
          git push origin HEAD:${{ github.ref_name }}
          git push --tags

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            
            Automated release for version ${{ github.ref_name }}
            
            ### Installation
            ```bash
            npm install otak-mcp-shell
            ```
            
            ### Usage
            ```bash
            # Shell MCP Server (stdio mode)
            npx otak-mcp-shell
            
            # HTTP Server mode (port 8768)
            npx otak-mcp-shell-http
            
            # MCP over HTTP mode (port 8767)
            npx otak-mcp-shell-mcp
            ```
            
            ### Features
            - Secure shell command execution with restrictions
            - Support for stdio, HTTP, and MCP over HTTP modes
            - Built-in security to block dangerous commands
            - Cross-platform support (Windows/Unix)
          draft: false
          prerelease: false
        continue-on-error: true